Set RABBITMQ_BASE for redirection to rabbitmq-* commands.

diff --git a/com.rabbitmq.jms/bin/setUpIntegrationTests b/com.rabbitmq.jms/bin/setUpIntegrationTests
--- a/com.rabbitmq.jms/bin/setUpIntegrationTests
+++ b/com.rabbitmq.jms/bin/setUpIntegrationTests
@@ -2,10 +2,15 @@
 
 echo Reset RabbitMQ server for Integration Tests
 
-sudo rabbitmqctl stop_app
-sudo rabbitmqctl reset
-# sudo rabbitmq-plugins enable rabbitmq_management
-sudo rabbitmq-plugins list -v
-sudo rabbitmqctl start_app
+if [ -z "${RABBITMQ_BASE}" ] ; then
+  echo "Couldn't find the RABBITMQ_BASE directory"
+  exit 1
+fi
+
+sudo ${RABBITMQ_BASE}/rabbitmqctl stop_app
+sudo ${RABBITMQ_BASE}/rabbitmqctl reset
+# sudo rabbitmq-plugins enable rabbitmq_rjms_topics
+sudo ${RABBITMQ_BASE}/rabbitmq-plugins list
+sudo ${RABBITMQ_BASE}/rabbitmqctl start_app
 
 echo RabbitMQ server reset
